### PR TITLE
Build wheels using cibuildwheel

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by davidbrochart** [comment]
@dmonad @Waidhoferj I heard you had issues building wheels with maturin, it seems to work fine with this PR (which uses cibuildwheel).

**Comment by SylvainCorlay** [comment]
@dmonad it would be great if this was merged. We have been blocked on this for a few weeks already!

**Comment by dmonad** [comment]
If I understand correctly, this only builds y-py, correct? What does this action do `actions/upload-artifact@v2`? 

The current build script releases a new y-py package on pypi using environment variables that I configured (I think it's my account). How does this script actually release the build?

**Comment by davidbrochart** [comment]
I just added the "Publish wheels to PyPI" step. It uses the same same secrets that you have in [main.yml](https://github.com/y-crdt/y-crdt/blob/main/.github/workflows/main.yml) (`secrets.PYPI_USERNAME` and `secrets.PYPI_PASSWORD`), and it is triggered when you push a tag.

**Comment by davidbrochart** [comment]
I removed the PyPI publishing for now, I will try it out with a dummy PyPI project.

**Comment by davidbrochart** [comment]
I just tested publishing on PyPI in this branch: https://github.com/davidbrochart/y-crdt/tree/test_pypi
It works, see the `yy-py` project: https://pypi.org/project/yy-py/0.2.2/#files
I installed it on my Linux machine with `pip install yy-py` and could `import y_py` successfully.
I'll push the changes here.

**Comment by Waidhoferj** [comment]
I'm all for it 👍

**Pull request merged**
