### PR TITLE
adopt ItemContent decoding logic to yrs

### LINKED ISSUE #254: decode ItemContent type with BLOCK_ITEM_FORMAT_REF_NUMBER from YJS causes error
Description:
when a content has a ref_number of 6 encoded from yjs, yrs cannot decode it properly, code snippet:

```
            BLOCK_ITEM_FORMAT_REF_NUMBER => Ok(ItemContent::Format(
                decoder.read_key()?,
                decoder.read_json()?.into(),
            )),
```

How to reproduce:

```
use yrs::Update;

Update::decode_v2(bin);

```

use the following binary

`AAMAAxDwAYKgz7Yewr7YzAwBqvemnR6tuvzPF4v+16gd+oahgRcAlea/jx26hqGBF5Xmv48d+oahgRcA1ea/jx0Erbr8zxeDkr2+EoOdmbQX3MGcngMFw52ZtBcHnMGcngO6hqGBF8OdmbQXBrqGoYEXs7mXrQ/6hqGBFwOzuZetD/qGoYEXBLO5l60Pg5K9vhLt0sKYBwHDkr2+EgCzuZetD6vxqs0NwqDPth4BtO60qQ3CvtjMDAKt0sKYB/qGoYEXAe3SwpgHAJzBnJ4D+oahgRcA3MGcngMFuoahgRfcwZyeAwO6hqGBF9zBnJ4DHunlpugCAGcKAwBOCgBKAQCEAQMACk4AwAEuAD4AAgBC5AECAQFCAAIOFlIBAgoEbgECCgEDSgMBAEYDAEQGAgQCBEwABEoDAAxQAQAYAkIBABoDAUIBAUIBAB4DAEIBAUIBAB4DAEIBAUIAfgByCQoMFGoBABYBAJMBoQCoAKEAqAAoAQcABADHAAcABgCEAIYAKAGoACgFhwAHACgFBwAEAMcAKAMHAAQARwAEAEcAKAPHACEBKAAhACgAwQAAAKgCJwAoAQEAAAAhAAAAqAIhAigAIQGhAqgCJwAoAccABwAGAIQAhgAoAccABwAEACgBxwAHAgQAKAWHAAcBBAAoBYcABwEEACgHJwAEsQfFBmNhcmRJZGJnSWTlhpnmlofmoaPjgIHorrDnrJTorrDigKbigKbkvaDog73mg7PliLDnmoTlhpnkvZzlnLrmma/vvIzpg73lj6/ku6XnlKhWZXJzZei9u+advuWujOaIkO+8gWhmb3JlY29sb3Lmlofnq6DnpLrkvovvvJpmb3JlY29sb3JsZXZlbGJfaWRiZ0NvbG9yY29sb3JiZ0NvbG9yY29sb3JiZ0NvbG9yY29sb3JsaXBpbmRlbnR0YWdOYW1lbGluZUhlaWdodGJfaWRjaGVja2VkYl9pZC9waW5kZW50dGFnTmFtZWxpbmVIZWlnaHRiX2lkLy9hYXBpbmRlbnR0YWdOYW1lbGluZUhlaWdodGJfaWRsaW5rbm90ZWd1aWRzbG90R3VpZHR5cGVsaW5rVHlwZWJfaWRsaW5rbm90ZXN6WjROX3otOFJTU0RBQnpCc0VONTFRMDFwcm9zZW1pcnJvcmxpbmtub3Rlc3ZwWDVYRXpxU1dhMFdhemFaZGNvV2dub3RlLnRhZ1lKWUpCT21WUzFXbW9xcUU3NGFvTmc65L2/55So5biu5Yqpbm90ZS5ndWlkbm90ZUd1aWRub3RlLm93bmVyb3duZXJub3RlLnR5cGVub3RlVHlwZW5vdGUucHJpdmF0ZWlzUHJpdmF0ZW5vdGUuY3JlYXRlVGltZWNyZWF0ZVRpbWVsaW5rbm90ZXNPZVRxdDIyclRlLTYyWHNMbTNLOHNBMDFoZm9yZWNvbG9y566A5Y2V5b6F5Yqe56S65L6LZm9yZWNvbG9ybGV2ZWxiX2lkaDTmnIgx5pel6LaF5biC6LSt54mp77yabGV2ZWxiX2lkdG9kb2xpc3RsaXDpuKHom4sqMktnaW5kZW50dGFnTmFtZWxpbmVIZWlnaHRiX2lkY2hlY2tlZGJfaWRsaXDpo5/nlKjnm5AqMeiii2luZGVudHRhZ05hbWVsaW5lSGVpZ2h0Yl9pZGNoZWNrZWRiX2lkbGlw4oCm4oCmaW5kZW50dGFnTmFtZWxpbmVIZWlnaHRiX2lkY2hlY2tlZGJfaWR0b2RvYl9pZG5vdGUudGl0bGV0aXRsZeekuuS+i+aWh+ahowYEIQEJBQkFBAcFBwUHBQIBBgcKBAcEQQAGBwoEAQMBBgcKBAgECAQIBAkWQQALCRYIGwkICgUJCAwJDwoJFkEBCQYJBQQBCQUECAIBRgAHCgQHBAIBRgAHCgQHBAIBAgYHCgQHRAEKBQQNACYBAAABAQgAJwEAABsGAwZDAAYDRgBDAEEAAwYDBkMBBkMABkMABgIKQSEEQQQEAQJBJw8DAHkBAHcBMQIAdwVjYXJkMncQYmdDb2xvcmJnQ29sb3IwMQkAdgEFY29sb3J3ByM5OTk5OUV+fQJ3CzB0dmFUU21UckVDAQB3ATEZAHcAdwB3AHcAdwB3AH0AdwNkaXZ3AHcLd21MOFJlWTNkVVZ5dwt2V2wzUTI1dkhDNX0AdwNkaXZ3AHcLd21MOFJlWTNkVVYNAH0AdwNkaXZ3AHcLbV85bVR5WWNCVkh3CGxpbmtub3RldwtYQzVtUzZRcGh2TwYAdxZ0RUkxTHZKM1ROT0pJOENhR3p1X3d3dxZ6WjROX3otOFJTU0RBQnpCc0VONTFRdwExdwExdxZ0RUkxTHZKM1ROT0pJOENhR3p1X3d3BAADAHcWVG5TZzFlMS1Td3UwVnV0Vkg0QWdxUXl3DTE2NTkwODg0ODc1MzMBAAgAfQAGAHcWNzExaC1iXzFTNXUxSTJOeDdWaXMzUXcWT2VUcXQyMnJUZS02MlhzTG0zSzhzQXcBMXcBMXcWNzExaC1iXzFTNXUxSTJOeDdWaXMzUS0AdgEFY29sb3J3ByM5OTk5OUV+fQJ3C3oxLUNTLXZ3b3dofQN3CzdFb3NULXpmajctfQB3A2RpdncAdwtSX1RfUldLbWRXNXh3C1ZNMDZTeUJTdE9nfQB3A2RpdncAdwtHaWlvU21Sb1pEX3l3C2tIVC1UNlFySDZKfQB3A2RpdncAdwtoODlIUzJyUUlza3l3C2p1cEZRT0FpTHVqeHcLMDdMUVNpTTBRTS0CAAmCn6ymBgIAAQEEgtCnmw8BAALz3MvWBwEAB7rD0MALAwYBAQABBK2pocwDAQAFg8menwkBAgCtnf7nCwEAALS32tQGAQAAw86M2gsCBgkFBQ==`

### PR DESCRIPTION
**Pull request by stellit**
in yjs, decoding is actually calling read_any instead. This change going to mirror the same logic to maximize the compatibility to yjs.

going to fix #254

### CODE REVIEW

**Comment by Horusiath** [comment]
@stellit I'll need more time to make sure that's indeed the case. Looking at [yjs repo](https://github.com/yjs/yjs/blob/370d0c138d6ffe9d5969e3371139896d45f1b7d2/src/structs/ContentFormat.js#L103) it seems that original code was correct.

**Comment by Horusiath** [comment]
It seems that actual problem was a little bit different - Yjs v1 JSON encoding uses naive `JSON.stringify`, while v2 used our own binary implementation. I've submitted a necessary PR in #257

**Comment by Horusiath** [comment]
@stellit I believe this should be fixed in yrs v0.16.1. Could you confirm if that's the case?

**Comment by stellit** [comment]
> It seems that actual problem was a little bit different - Yjs v1 JSON encoding uses naive `JSON.stringify`, while v2 used our own binary implementation. I've submitted a necessary PR in #257

Hi Bartosz,

#257 Indeed fix the issue, it seems replace the read_key with read_string is not a good idea. the just need to use decode any while read json.

Thanks a lot!

**Pull request closed without merging**
